[project]
name = "marimo-pm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair==6.2.2",
    "eclear==0.1.0",
    "marimo==0.24.0",
    "numpy==2.5.2",
    "pandas==3.0.5",
    "plotly==7.0.0",
    "pm4py==2.7.22.3",
    "polars>=1.44.1",
    "pyarrow>=25.0.1",
    "pytz==2026.2",
    "r4pm>=0.6.2",
]
